---
- hosts: all
  become: yes
  tasks:
    -name: update ubuntu package and install apache2
    apt: 
      name: apache2
      update_cache: yes
      state: present
    -name: restart_apache2
    service:
      name: apache2
      state: restarted
