---
- hosts: all
  become: yes
  tasks:
  - name: download a file
    get_url:
      url: https://github.com/srinivas-reddy-mula/warfiles/blob/master/gameoflife.war
      dest: /var/lib/tomcat8/webapps/
